{
 "title": "Redis Stats",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "command rates (rpm)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_traffic_stats_command_count{job=\"redis-stats\"}[5m]) * 60 > 5000",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "key rates (rpm)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_traffic_stats_command_detail_count{job=\"redis-stats\"}[5m]) * 60 > 5000",
     "legendFormat": "{{command}} {{args}}"
    }
   ]
  },
  {
   "title": "command counts",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis_traffic_stats_command_count{job=\"redis-stats\"}",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "key counts",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_traffic_stats_command_detail_count{job=\"redis-stats\"}"
    }
   ]
  }
 ]
}